// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00fip9oRFzQ36Y9YLZRojSpj-BT8s8lY',
    appId: '1:1082445479120:web:b0f2c428dbc4740c9272d5',
    messagingSenderId: '1082445479120',
    projectId: 'zoom-clone-5ac2a',
    authDomain: 'zoom-clone-5ac2a.firebaseapp.com',
    storageBucket: 'zoom-clone-5ac2a.appspot.com',
    measurementId: 'G-4MKE4Z5BZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5K-X63KajOqQIg76QhcNU3B50hajQ44',
    appId: '1:1082445479120:android:778c285243227e0d9272d5',
    messagingSenderId: '1082445479120',
    projectId: 'zoom-clone-5ac2a',
    storageBucket: 'zoom-clone-5ac2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UGIA21W7PdeAEO1Hq7v8DOh8MQY3jJg',
    appId: '1:1082445479120:ios:0cbdd8a08545a8109272d5',
    messagingSenderId: '1082445479120',
    projectId: 'zoom-clone-5ac2a',
    storageBucket: 'zoom-clone-5ac2a.appspot.com',
    iosClientId: '1082445479120-862qalnap92luhm3qf1bieimmo203t56.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UGIA21W7PdeAEO1Hq7v8DOh8MQY3jJg',
    appId: '1:1082445479120:ios:0cbdd8a08545a8109272d5',
    messagingSenderId: '1082445479120',
    projectId: 'zoom-clone-5ac2a',
    storageBucket: 'zoom-clone-5ac2a.appspot.com',
    iosClientId: '1082445479120-862qalnap92luhm3qf1bieimmo203t56.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoom',
  );
}
